"""add decision relationship graph

Revision ID: 815dd10ddc9d
Revises: 774e747936aa
Create Date: 2026-07-13 04:54:53.040091
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '815dd10ddc9d'
down_revision: Union[str, None] = '774e747936aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_entities',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'entity_type', 'normalized_name', name='uq_graph_entity_workspace_type_name')
    )
    op.create_index(op.f('ix_graph_entities_entity_type'), 'graph_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_graph_entities_normalized_name'), 'graph_entities', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_graph_entities_workspace_id'), 'graph_entities', ['workspace_id'], unique=False)
    op.create_table('graph_relationships',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['graph_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['graph_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entity_id', 'target_entity_id', 'relationship_type', name='uq_graph_relationship')
    )
    op.create_index(op.f('ix_graph_relationships_relationship_type'), 'graph_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_graph_relationships_source_entity_id'), 'graph_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_graph_relationships_target_entity_id'), 'graph_relationships', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_graph_relationships_workspace_id'), 'graph_relationships', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_relationships_workspace_id'), table_name='graph_relationships')
    op.drop_index(op.f('ix_graph_relationships_target_entity_id'), table_name='graph_relationships')
    op.drop_index(op.f('ix_graph_relationships_source_entity_id'), table_name='graph_relationships')
    op.drop_index(op.f('ix_graph_relationships_relationship_type'), table_name='graph_relationships')
    op.drop_table('graph_relationships')
    op.drop_index(op.f('ix_graph_entities_workspace_id'), table_name='graph_entities')
    op.drop_index(op.f('ix_graph_entities_normalized_name'), table_name='graph_entities')
    op.drop_index(op.f('ix_graph_entities_entity_type'), table_name='graph_entities')
    op.drop_table('graph_entities')
    # ### end Alembic commands ###
